apiVersion: v1
kind: Service
metadata:
  name: doh-proxy-service
  namespace: doh3-proxy
spec:
  selector:
    app: doh-proxy-server
  ports:
    - protocol: TCP
      name: dns-tcp
      port: 53
      targetPort: 5353
    - protocol: UDP
      name: dns-udp
      port: 53
      targetPort: 5353
  type: ClusterIP
  